quotes = [
"""I played in a death-metal band. People either loved us or hated us… or they thought we were OK.""",
"""A severed foot is the ultimate stocking stuffer.""",
"""They say Flintstone's vitamins are chewable; all vitamins are chewable, it's just that they taste shitty.""",
"""If you wear a turtleneck and a backpack it's like a weak midget trying to bring you down.""",
"""I don't like grouper fish.  Well, they're okay.  They hang around star fish.  Because they're grouper fish.""",
"""I wrote a script and gave it to a guy that reads scripts, and he read it and said he really likes it, but he thinks I need to rewrite it; I said, f**k that, I'll just make a copy.""",
"""Yeah, this comedy is all a part of my “Get Rich Slow” scheme… and it’s working.""",
"""If you don’t know a light bulb is a three-way light bulb, it messes with your head. You reach to turn it off, and it just gets brighter! That’s the exact opposite of what I wanted you to do!""",
"""I want to get a vending machine, with fun sized candy bars, and the glass in front is a magnifying glass. You'll be mad, but it will be too late.""",
"""I saw this wino, he was eating grapes… I was like, "Dude, you have to wait.""",
"""I spilled some vodka on the carpet, and I vacuumed it up, and the vacuum got drunk. I had to take the Hoover to detox.""",
"""If a drink was ice cold, it would be impossible to drink. Because it would be solid. “Here's a drink, Mitch – it's ice cold.” I guess I could lick it.""",
"""I wanna hang a map of the world in my house – then I'm gonna put pins into all the locations that I've travelled to; but first, I'm gonna have to travel to the top two corners of the map so that it will not fall off the wall.""",
"""Every book is a children's book if the kid can read.""",
"""I was walking by a dry cleaner at 3 a.m., and it said "Sorry, we're closed" … you don't have to be sorry – it's 3 a.m., and you're a dry cleaner.""",
"""I don't own a cell phone or a pager; I just hang around everyone I know, all the time.""",
"""I remixed a remix… it was back to normal.""",
"""I had a paper route when I was a kid and I was supposed to go to 2,000 houses… or two dumpsters.""",
"""You know, you can't please all the people all the time… and last night, all those people were at my show.""",
"""When I was on acid, I'd see things like beams of light and I'd hear sounds that sounded an awful lot like car horns.""",
"""I find that a duck's opinion of me is heavily influenced by whether or not I have bread.""",
"""I went to a doctor, and all he did is suck blood from my neck; don't go see Dr. Acula.""",
"""I sometimes close my eyes during a show because I have drawn a picture of an audience enjoying the show more on the back of my eyelids.""",
"""I once saw a forklift lift a crate of forks… and it was way to literal for me.""",
"""I wanted to get my teeth whitened, but I said, "F**k that… I'll just get a tan instead.""",
"""I wanna hang a map of the world in my house – then I'm gonna put pins into all the locations that I've travelled to; but first, I'm gonna have to travel to the top two corners of the map so that it will not fall off the wall.""",
"""I order the club sandwich all the time, but I'm not even a member, man.""",
"""I'm sick of 'soup of the day,' it's time we made a decision.""",
"""I love my Fed-Ex guy cause he's a drug dealer and he doesn't even know it…and he's always on time.""",
"""Here's a thought for sweat shop owners: air conditioning… problem solved.""",
"""Last week I helped my friend stay put – it’s a lot easier than helping someone move – I just went over to his house and made sure that he did not start to load shit into a truck.""",
"""I would not want to be a mobile home repo man…  Knock knock… “Hi, would you go cut your grass and look that way for a half an hour?”""",
"""Is a hippopotamus a hippopotamus, or just a really cool Opotamus?""",
"""I think Pringle’s intention was to make tennis balls, but the day the rubber was supposed to show up, they got a big load of potatoes instead; but Pringles was a laid-back company and they said, "f**k it, cut 'em up."""",
"""What's a sesame seed grow into? … I don't know we never give them a chance… what the f**k is a sesame?! … it's a street… it's a way to open shit…""",
"""You should never tell someone they have a nice dimple, because maybe they were shot in the face with a BB gun.""",
"""If a drink was ice cold, it would be impossible to drink. Because it would be solid. “Here's a drink, Mitch – it's ice cold.” I guess I could lick it.""",
"""If you're a fish, and you want to be a fish stick, you must have very good posture.""",
"""I would imagine if you could understand Morse Code, a tap dancer would drive you crazy.""",
"""I've been sitting my whole life, and a dog has never looked at me as though he thought I was tricky.""",
"""Alcoholism is a disease, but it's the only disease that you can get yelled at for having.""",
"""When I was a boy, I laid in my twin size bed, wondering where my brother was.""",
"""Rice is great if you're hungry and want 2000 of something.""",
"""I think Foosball© is a combination of soccer and shish kabobs.""",
"""I have an idea for sweatshops: air conditioning!  That's simple.""",
"""I met this girl, she was an actress, and she gave me her number; it started with 555.""",
"""If 13 is unlucky, then 12 and 14 are guilty by association.""",
"""When I was a boy, I laid in my twin-sized bed and wondered where my brother was.""",
"""If I was on death row and given one last meal I would ask for a fortune cookie; “Come on ‘long prosperous life!’”""",
"""I would like it if four people did a cartwheel all at once… so I can make a cart.""",
"""People who live in glass houses shouldn't throw stones; unless, of course, they enjoy many broken windows.""",
"""They say Flintstone's vitamins are chewable; all vitamins are chewable, it's just that they taste shitty.""",
"""A lot of bars have black lights, and when a bar has black lights, everybody looks very cool…  except for me because I was under the impression that the mustard stain came out.""",
"""I can whistle with my fingers, especially if I have a whistle.""",
"""I don't own a cell phone or a pager; I just hang around everyone I know, all the time.""",
"""I want to get non-aerosol mace, you just rub it in. "Dude who is attacking me – come a little closer!""",
"""I had my palm read; I wrote something on it first to see if she would read that too.""",
"""I angered the clerk in a clothing shop today; she asked me what size I was and I said actual, because I am not to scale.""",
"""You know they call corn-on-the-cob – """,
"""I wanna hang a map of the world in my house – then I'm gonna put pins into all the locations that I've travelled to; but first, I'm gonna have to travel to the top two corners of the map so that it will not fall off the wall.""",
"""I think animal crackers make people think that all animals taste the same.""",
"""I've never been in a rotating restaurant, but one time I took my girlfriend to a merry-go-round, I put her on it, and I gave her a burrito.""",
"""Is a hippopotamus a hippopotamus, or just a really cool Opotamus?""",
"""I wrote a script and gave it to a guy that reads scripts and he read it and said he really likes it, but he thinks I need to rewrite it; I said, f**k that, I'll just make a copy.""",
"""A lollipop is a cross between hard candy and garbage.""",
"""I'm sick of 'soup of the day,' it's time we made a decision.""",
"""If I had a dollar for every time I said that, I'd be making money in a very weird way.""",
"""Fish are always eating other fish; if fish could scream, the ocean would be loud as shit.""",
"""You should never tell someone they have a nice dimple, because maybe they were shot in the face with a BB gun.""",
"""I have an idea for sweatshops: air conditioning!  That's simple.""",
"""I used to do drugs; I still do, but I used to, too.""",
"""My manager said, "Don't use liquor as a crutch!" I can't use liquor as a crutch, because a crutch helps me walk.""",
"""I rented a car.  I didn't really need one, I just wanted to make one less available.  I wanted one businessman on the bus with no car.""",
"""A lot of bars have black lights, and when a bar has black lights, everybody looks very cool…  except for me because I was under the impression that the mustard stain came out.""",
"""I don't own a cell phone or a pager. I just hang around everyone I know, all the time.""",
"""A lot of people don't know it, but onions make me sad!""",
"""I haven't slept for ten days… because that would be too long.""",
"""I have no problem not listening to """,
"""If you wear a turtleneck and a backpack it's like a weak midget trying to bring you down.""",
"""I was walking by a dry cleaner at 3 a.m., and it said "Sorry, we're closed" … you don't have to be sorry – it's 3 a.m., and you're a dry cleaner.""",
"""If I had nine of my fingers missing I wouldn't type any slower.""",
"""If a drink was ice cold, it would be impossible to drink. Because it would be solid. “Here's a drink, Mitch – it's ice cold.” I guess I could lick it.""",
"""Fish are always eating other fish; if fish could scream, the ocean would be loud as shit.""",
"""2-in-1 is a stupid term, because 1 is not big enough to hold 2; that's why 2 was created.""",
"""If you drink O'Douls, you don't drink; and if you drink twenty… you're a non-alcoholic.""",
"""I have some speakers up here, thank God, because last night I didn't have them and I was telling jokes and I had no idea which joke I was telling. So I told jokes twice. I even told that one twice.""",
"""I'm sick of 'soup of the day,' it's time we made a decision.""",
"""A severed foot is the ultimate stocking stuffer.""",
"""Spaghetti… I can't eat spaghetti, there's too many of them.  No matter how hungry I am, 1000 of something is too many.""",
"""I want to rob a bank with a BB gun. “Give me all your money or I will give you a dimple! I will be rich, you will be cute. We both win.”""",
"""You know, I'm sick of following my dreams, man; I'm just going to ask where they're going and hook up with 'em later.""",
"""People who live in glass houses shouldn't throw stones; unless, of course, they enjoy many broken windows.""",
"""I would imagine if you could understand Morse Code, a tap dancer would drive you crazy.""",
"""You know they call corn-on-the-cob – """,
"""I went to a pizzeria, I ordered a slice of pizza, the f**ker gave me the smallest slice possible; if the pizza was a pie chart for what people would do if they found a million dollars, the f**ker gave me the “donate it to charity” slice.""",
"""I played golf. I did not get a hole in one, but I did hit a guy. … you're supposed to yell, """,
"""I bought a seven-dollar pen because I always lose pens and I got sick of not caring.""",
"""I had a piece of Carefree Sugarless gum and I was still worried; it never kicked in.""",
"""It's hard to fight when you're in a gazebo.""",
"""If I was on death row and given one last meal I would ask for a fortune cookie; “Come on ‘long prosperous life!’”""",
"""If you wear a turtleneck and a backpack it's like a weak midget trying to bring you down.""",
"""I don't own a cell phone or a pager; I just hang around everyone I know, all the time.""",
"""A waffle is like a pancake with a syrup trap.""",
"""Imagine if you were a drummer, and you accidentally picked up two magic wands instead of sticks; there you are, keeping the beat, the next thing you know, your bass player turns into a can of soup.""",
"""If Spiderman was real, and I was a criminal, and he shot me with his web, I would say, “Dude, thanks for the hammock.”""",
"""I don't have a girlfriend but I do know a woman who'd be mad at me for saying that.""",
"""Cavities are made by sugar.  So if you need to dig a hole, then lay down some candy bars!""",
"""If you find yourself lost in the woods, f**k it, build a house; "Well, I was lost but now I live here!”""",
"""My girl works at Hooters… in the kitchen.""",
"""Imagine if the headless horseman had a headless horse… that would be chaos""",
"""I wanna hang a map of the world in my house – then I'm gonna put pins into all the locations that I've travelled to; but first, I'm gonna have to travel to the top two corners of the map so that it will not fall off the wall.""",
"""I bought a seven-dollar pen because I always lose pens and I got sick of not caring.""",
"""I went to a pizzeria, I ordered a slice of pizza, the f**ker gave me the smallest slice possible; if the pizza was a pie chart for what people would do if they found a million dollars, the f**ker gave me the “donate it to charity” slice.""",
"""I like vending machines, because snacks are better when they fall; if I buy a candy bar at the store, oftentimes I will drop it, so that it achieves its maximum flavor potential.""",
"""Yeah, this comedy is all a part of my “Get Rich Slow” scheme… and it’s working.""",
"""I was walking by a dry cleaner at 3 a.m., and it said "Sorry, we're closed" … you don't have to be sorry – it's 3 a.m., and you're a dry cleaner.""",
"""By the way, you don't have to be sweaty and holding a basketball to enjoy a Gatorade; you could just be a thirsty dude; Gatorade forgets about this demographic!""",
"""On a traffic light green means 'go' and yellow means 'yield', but on a banana it's just the opposite; green means 'hold on,' yellow means 'go ahead,' and red means, 'where the f**k did you get that banana at?'""",
"""I wrote my friend a letter using a highlighting pen but he could not read it, he thought I was just trying to show him certain parts of a piece of paper.""",
"""I tried to walk into Target, but I missed.""",
"""I went to a pizzeria, I ordered a slice of pizza, the f**ker gave me the smallest slice possible; if the pizza was a pie chart for what people would do if they found a million dollars, the f**ker gave me the “donate it to charity” slice.""",
"""Knock on wood is a saying for good luck. I think that started when someone went to someone's door to see if someone was home. “I hope Joe's home, knock on wood!”""",
"""Remember that show """,
"""They say """,
"""I sometimes close my eyes during a show because I have drawn a picture of an audience enjoying the show more on the back of my eyelids.""",
"""2-in-1 is a stupid term, because 1 is not big enough to hold 2; that's why 2 was created.""",
"""I had a chicken finger that was so big, it was a chicken hand.""",
"""What am I drinking? … NyQuil on the rocks, for when you're feeling sick but sociable.""",
"""I'd like to make a vending machine that sells vending machines; it'd have to be real big!""",
"""Why are there no “during” pictures?""",
"""Some people think I'm high on stage; I would never get high before a show, because, when I'm high, I don't wanna stand in front of a bunch of people I don't know.""",
"""I remixed a remix… it was back to normal.""",
"""I can't wait to get off the stage, because I've got some LifeSavers in my pocket and pineapple is next!""",
"""I can read minds but, it’s pointless cause I’m illiterate.""",
"""If you're flammable and have legs, you're never blocking a fire exit.""",
"""I wrote a script and gave it to a guy that reads scripts, and he read it and said he really likes it, but he thinks I need to rewrite it; I said, f**k that, I'll just make a copy.""",
"""My friend asked me if I wanted a frozen banana, I said “No, but I want a regular banana later, so… yeah.”""",
"""On a traffic light yellow means yield, and green means go; on a banana, it’s just the opposite, yellow means go ahead, green means stop, and red means, "Where’d you get that banana?""",
"""I find that a duck's opinion of me is heavily influenced by whether or not I have bread.""",
"""Imagine if you were a drummer, and you accidentally picked up two magic wands instead of sticks; there you are, keeping the beat, the next thing you know, your bass player turns into a can of soup.""",
"""I wear a necklace, cause I wanna know when I'm upside down.""",
"""Every book is a children's book if the kid can read.""",
"""Kinko's is my favorite copy place cause it's open 24 hours, like if it's three in the morning, and I suddenly decide I need two of something, I'm covered.""",
"""When I was a boy, I laid in my twin size bed, wondering where my brother was.""",
"""I went to a pizzeria, I ordered a slice of pizza, the f**ker gave me the smallest slice possible; if the pizza was a pie chart for what people would do if they found a million dollars, the f**ker gave me the “donate it to charity” slice.""",
"""Fettucini Alfredo is macaroni and cheese for adults.""",
"""If you wear a turtleneck and a backpack it's like a weak midget trying to bring you down.""",
"""Remember that show """,
"""I wrote my friend a letter using a highlighting pen but he could not read it, he thought I was just trying to show him certain parts of a piece of paper.""",
"""I played in a death-metal band. People either loved us or hated us… or they thought we were OK.""",
"""I have an underwater camera just in case I crash my car into a river, and at the last minute I see a photo opportunity of a fish that I have never seen.""",
"""Some people think I'm high on stage; I would never get high before a show, because, when I'm high, I don't wanna stand in front of a bunch of people I don't know.""",
"""When I was on acid, I'd see things like beams of light and I'd hear sounds that sounded an awful lot like car horns.""",
"""What am I drinking? … NyQuil on the rocks, for when you're feeling sick but sociable.""",
"""I remixed a remix… it was back to normal.""",
"""I rented a car.  I didn't really need one, I just wanted to make one less available.  I wanted one businessman on the bus with no car.""",
"""I played golf. I did not get a hole in one, but I did hit a guy. … you're supposed to yell, """,
"""I don't have a girlfriend but I do know a woman who'd be mad at me for saying that.""",
"""If you drink O'Douls, you don't drink; but if you drink 20 O'Douls in a half hour, then you're a non-alcoholic.""",
"""Magicians disappear all the time, but as soon as a regular person does it, everyone is all scared… “Tom's gone! … Is he a magician?”… “No. … then let's print up some flyers!”""",
"""I can read minds but, it’s pointless cause I’m illiterate.""",
"""If you have to release bad news to the public, it would help if you are not ugly.""",
"""Kinko's is my favorite copy place cause it's open 24 hours, like if it's three in the morning, and I suddenly decide I need two of something, I'm covered.""",
"""I think animal crackers make people think that all animals taste the same.""",
"""If you drink O'Douls, you don't drink; and if you drink twenty… you're a non-alcoholic.""",
"""If you're flammable and have legs, you're never blocking a fire exit.""",
"""Fish are always eating other fish; if fish could scream, the ocean would be loud as shit.""",
"""I want to ride in a cold air balloon; "This isn't going anywhere!""",
"""My manager said, "Don't use liquor as a crutch!" I can't use liquor as a crutch, because a crutch helps me walk.""",
"""I went to a restaurant with my friend, and he said, "Pass the salt;" I said, "Screw you! Sit closer to the salt.""",
"""Imagine if the headless horseman had a headless horse… that would be chaos""",
"""I wrote a script and gave it to a guy that reads scripts, and he read it and said he really likes it, but he thinks I need to rewrite it; I said, f**k that, I'll just make a copy.""",
"""I have a vest; if I had my arms cut off, it would be a jacket.""",
"""I used to be a hot-tar roofer… yeah, I remember that day.""",
"""I got binoculars ’cause I don’t want to go that close.""",
"""I was walking by a dry cleaner at 3 a.m., and it said "Sorry, we're closed" … you don't have to be sorry – it's 3 a.m., and you're a dry cleaner.""",
"""Spaghetti… I can't eat spaghetti, there's too many of them.  No matter how hungry I am, 1000 of something is too many.""",
"""I want to get a vending machine, with fun sized candy bars, and the glass in front is a magnifying glass. You'll be mad, but it will be too late.""",
"""I saw this wino, he was eating grapes, and I was like, "Dude, you have to wait.”""",
"""My girl works at Hooters… in the kitchen.""",
"""Remember that show """,
"""You know, you can't please all the people all the time… and last night, all those people were at my show.""",
"""If you're a fish, and you want to be a fish stick, you must have very good posture.""",
"""My roommate said to me, 'I'm gonna go shave and use the shower; does anyone need to use the bathroom?' … it's like some weird ass quiz where he reveals the answer first.""",
"""A fly was very close to being called a “land,” cause that's what they do half the time.""",
"""I saw on HBO they were advertising a boxing match: “It's a fight to the finish” … that's a good place to end.""",
"""I'd hate to be a giraffe with a sore throat.""",
"""I like Kit-Kats unless I'm with four or more people.""",
"""I have a vest; if I had my arms cut off, it would be a jacket.""",
"""I saw this wino, he was eating grapes… I was like, "Dude, you have to wait.""",
"""On a traffic light yellow means yield, and green means go; on a banana, it’s just the opposite, yellow means go ahead, green means stop, and red means, "Where’d you get that banana?""",
"""I can look at a car’s headlights and tell you exactly which way it’s coming.""",
"""I got binoculars ’cause I don’t want to go that close.""",
"""Snake eyes is a gambling term… and an animal term, too.""",
"""If I was on death row and given one last meal I would ask for a fortune cookie; “Come on ‘long prosperous life!’”""",
"""I got a smoke alarm at home… but really it's more like a 9-volt-battery-slowly-drainer.""",
"""I want to ride in a cold air balloon; "This isn't going anywhere!""",
"""I went to a cigar store, the man behind the counter asked me, "What kind of cigars do you like?" and I answered, "It's a Boys.""",
"""I have a friend who is a juggler. If I'm at his house, I don't like to take food from him, if it's in threes.""",
"""I used to be a hot-tar roofer… yeah, I remember that day.""",
"""If I was on death row and given one last meal I would ask for a fortune cookie; “Come on ‘long prosperous life!’”""",
"""It’s weird… people say they’re not like apes, but how do you explain football then?""",
"""If I had nine of my fingers missing I wouldn't type any slower.""",
"""I wanna hang a map of the world in my house – then I'm gonna put pins into all the locations that I've travelled to; but first, I'm gonna have to travel to the top two corners of the map so that it will not fall off the wall.""",
"""When I was a boy, I laid in my twin-sized bed and wondered where my brother was.""",
"""I went to a doctor, and all he did is suck blood from my neck; don't go see Dr. Acula."""]